### ISSUE TITLE
GitLab not Github

### ISSUE THREAD

**Issue by ngaxavi** [ChristinaEs/33311290#1]
Die Aufgabe muss in Gitlab, nicht in Github gepusht werden. Falls du keinen Gitlab-Account hast erstelle dir einen. Danch gibst du mir Master-Rechte damit ich die Korrektur pushen kann

**Comment by ChristinaEs** [comment]
Achso ok, Prof Zündorf meinte es wäre egal ob Github oder Gitlab! Ich erstelle mir gleich einen Account
